CREATE TABLE service_user (
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(50) NOT NULL,
                        email varchar(50),
                        password varchar(50),
                        date_of_creation date
);

CREATE TABLE quote (
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       content varchar NOT NULL,
                       date_of_creation date,
                       date_of_update date,
                       user_id int REFERENCES service_user(id) ON DELETE CASCADE,
                       votes int default 0
);

