CREATE TABLE Person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    year_of_birth int NOT NULL
);

CREATE TABLE Book (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(50) NOT NULL,
    author varchar(50) NOT NULL,
    year int NOT NULL,
    person_id int REFERENCES Person(id) ON DELETE SET NULL,
    date_of_borrowing date
);

CREATE TABLE Person (
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(50) NOT NULL,
                        email varchar(50),
                        password varchar(50),
                        date_of_creation date
);

CREATE TABLE Quote (
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       content varchar NOT NULL,
                       date_of_creation date,
                       date_of_update date,
                       user_id int REFERENCES service_user(id) ON DELETE CASCADE,
                       votes int default 0
);

